name: Publish Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  goreleaser:
    name: Build and Publish via GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The automatically-creeated token wont work for updating the tap since the tap lives in
          # another repository. A separate key will need to be stored in the actions secrets that
          # has repo: write permissions to the tap repo.
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
